### ISSUE TITLE
LineSegmentation::sieve

### ISSUE THREAD

**Issue by jwijffels** [DIGI-VUB/image.textlinedetector#5]
Hello @arthurflor23

I've been using your C++ code at https://github.com/arthurflor23/text-segmentation to incorporate in this R package to facilitate my life to check on some algorithms for text line segmenation. When looking at the code, especially code https://github.com/arthurflor23/text-segmentation/blob/master/src/imgproc/cpp/LineSegmentation.cpp#L30 it seems to contain bugs. 
Function` LineSegmentation::sieve` should be written similarly as below, otherwise the primes vector does not contain prime numbers.

```
   bool notPrimesArr[100007];
   std::vector<int> primes;
    for (int i=0; i<1e5; ++i) {
      notPrimesArr[i] = false;
    }
    notPrimesArr[0] = notPrimesArr[1] = true;
    for (int i=2; i<1e5; ++i) {
      if (notPrimesArr[i]) continue;
      
      primes.push_back(i);
      for (int j=i*2; j<1e5; j += i) {
        notPrimesArr[j] = true;
      }
    }
```

If you use the current logic you implemented at https://github.com/arthurflor23/text-segmentation/blob/master/src/imgproc/cpp/LineSegmentation.cpp#L30, you would even have numbers 6, 22, 38 as prime numbers as your `if (notPrimesArr[i])` gives undefined behaviour

**Comment by arthurflor23** [comment]
Oh thanks, I updated

**Comment by jwijffels** [comment]
you probably should remove line https://github.com/arthurflor23/text-segmentation/blob/master/src/imgproc/cpp/LineSegmentation.cpp#L31 and https://github.com/arthurflor23/text-segmentation/blob/master/src/imgproc/cpp/LineSegmentation.cpp#L32 as they are already defined at https://github.com/arthurflor23/text-segmentation/blob/master/src/imgproc/cpp/LineSegmentation.hpp#L130

**Comment by arthurflor23** [comment]
Thanks again!

**Comment by jwijffels** [comment]
Thanks for updating.
